#nullable enable
using Microsoft.Maui.Storage;

namespace Luso.Features.Rooms.Networking.Hue
{
    /// <summary>
    /// Persists and retrieves Hue Bridge API keys (usernames generated by the link-button
    /// pairing flow) using <see cref="Microsoft.Maui.Storage.Preferences"/>.
    ///
    /// Keys are keyed by the bridge ID returned by the mDNS locator so that each
    /// physical bridge stores its own credential independently.
    /// </summary>
    internal static class HueBridgeAuth
    {
        private const string KeyPrefix = "hue_apikey_";
        private const string ClientKeyPrefix = "hue_clientkey_";
        private const string AppIdPrefix = "hue_appid_";
        private const string KnownBridgesKey = "hue_known_bridges";

        // ── API keys ──────────────────────────────────────────────────────────

        /// <summary>Returns the stored API key for <paramref name="bridgeId"/>, or <c>null</c> if not yet paired.</summary>
        public static string? GetApiKey(string bridgeId)
            => Preferences.Default.Get<string?>($"{KeyPrefix}{bridgeId}", null);

        /// <summary>Persists <paramref name="apiKey"/> for <paramref name="bridgeId"/>.</summary>
        public static void StoreApiKey(string bridgeId, string apiKey)
            => Preferences.Default.Set($"{KeyPrefix}{bridgeId}", apiKey);

        /// <summary>Removes the stored API key (e.g. if the user wants to re-pair).</summary>
        public static void ClearApiKey(string bridgeId)
            => Preferences.Default.Remove($"{KeyPrefix}{bridgeId}");

        // ── Client key (DTLS PSK for Entertainment API) ───────────────────────

        /// <summary>Returns the 32-char hex client key, or <c>null</c> if not available.</summary>
        public static string? GetClientKey(string bridgeId)
            => Preferences.Default.Get<string?>($"{ClientKeyPrefix}{bridgeId}", null);

        /// <summary>Persists the Entertainment API client key (32-char hex).</summary>
        public static void StoreClientKey(string bridgeId, string clientKey)
            => Preferences.Default.Set($"{ClientKeyPrefix}{bridgeId}", clientKey);

        // ── Application ID (DTLS PSK identity for Entertainment API) ──────────

        /// <summary>Returns the hue-application-id, or <c>null</c> if not fetched yet.</summary>
        public static string? GetApplicationId(string bridgeId)
            => Preferences.Default.Get<string?>($"{AppIdPrefix}{bridgeId}", null);

        /// <summary>Persists the hue-application-id returned by GET /auth/v1.</summary>
        public static void StoreApplicationId(string bridgeId, string appId)
            => Preferences.Default.Set($"{AppIdPrefix}{bridgeId}", appId);

        // ── Known bridge IPs (fast-path discovery cache) ──────────────────────

        /// <summary>
        /// Returns all previously discovered bridges as (BridgeId, IpAddress) pairs.
        /// Stored as a semicolon-delimited list so a single Preferences key suffices
        /// (MAUI Preferences does not support key enumeration).
        /// </summary>
        public static IReadOnlyList<(string BridgeId, string Ip)> GetKnownBridges()
        {
            var raw = Preferences.Default.Get<string?>(KnownBridgesKey, null);
            if (string.IsNullOrEmpty(raw)) return Array.Empty<(string, string)>();
            return raw.Split(';', StringSplitOptions.RemoveEmptyEntries)
                      .Select(e => e.Split('|'))
                      .Where(p => p.Length == 2)
                      .Select(p => (p[0], p[1]))
                      .ToList();
        }

        /// <summary>Upserts the last known IP for a bridge (called after every successful connect).</summary>
        public static void StoreKnownBridge(string bridgeId, string ip)
        {
            var existing = GetKnownBridges()
                .Where(b => b.BridgeId != bridgeId)
                .ToList();
            existing.Add((bridgeId, ip));
            Preferences.Default.Set(KnownBridgesKey,
                string.Join(";", existing.Select(b => $"{b.BridgeId}|{b.Ip}")));
        }
    }
}
